### ISSUE TITLE
Correct text in the FAQ

### ISSUE THREAD

**Issue by ceneblock** [objectcomputing/OCITAO#2]
When browsing the FAQ, I noticed that there are instances 

```{{site.baseurl}}``` appearing on the page. If possible, could someone fix the link text?

If there is any additional information that I can provide, then please let me know.

Site: https://objectcomputing.github.io/OCITAO/support/faq.html#OCI_Specific
Screen shot:
![Screenshot at 2019-06-12 13-01-43](https://user-images.githubusercontent.com/18190995/59376812-80ba4a00-8d16-11e9-9bbf-71d8bd2db242.png)

**Comment by mitza-oci** [comment]
@tottens I think these need to be changed from `{{site.baseur}}` to just having the actual URL

**Comment by tottens** [comment]
@mitza-oci I don't think I have an account for that repo. I'll look into it.

**Comment by mitza-oci** [comment]
Fixed in #3
